- src/planet-4-151612/wordpress/etc/my_init.d/20_install_wordpress.sh
Ref: https://jira.greenpeace.org/browse/PLANET-5158
Follows: #47 
A command `make nro-enable` would return an error because `/app/.composer` is owned by `root`.  
This was caused by #47, composer now doesn't execute a full chown before running, which keeps original rights on files.
- Run `composer` with user `app` when possible
- Give ownership of composer related files to `app`
- Fixed `_warn` function to `_warning`  
`_warn` does not exist
- Made the `cat "${PUBLIC_PATH}/index.php"` ok with `index.php` not existing  
stumbled on the error while doing some test, doesn't look like it should fail
A `make dev` followed by `make nro-enable` shouldn't raise any access rights error.
> PLANET-5158: Give composer files to user app

- src/planet-4-151612/wordpress/wp-config.php.tmpl
This would solve the issue of CLI not using the correct site url, and I don't think we need the image to be able to work with a different hostname on the fly, but maybe I'm missing something :thinking: 
`APP_HOSTPATH` already has the "/" prepended, it is added somewhere before.
I also modified the fallback when `HTTP_HOST` is not set to use the same value, instead of an empty string. Note that it had always had an empty string there, so some things that never worked might start working, which could cause issues.
> Add hostname as string literal

- src/planet-4-151612/wordpress/wp-config.php.tmpl
It looks like the protocol variable is needed when docker-compose is ran in CI, so I added this part again that was removed in https://github.com/greenpeace/planet4-docker/pull/56
Tested on master-theme: https://app.circleci.com/pipelines/github/greenpeace/planet4-master-theme/2518/workflows/d5b45307-df4f-4161-8721-800e7ac515c7/jobs/12743 The workflow still fails there, but after the point where it got stuck before, and due to changes in the repo itself.
> Re-add protocol config

- src/planet-4-151612/wordpress/etc/my_init.post_shutdown.d/20_cleanup.sh
When the wordpress container crashes during wordpress install, the install lock file can stay there and block any subsequent install attempt, until container is destroyed.
This lock is mentioned in logs but not visible to the user waiting for its install to finish, which leads to neverending waiting times and a puzzled end-user.
Make sure the install lock file is removed by adding a cleanup script to the shutdown process, so that when the install fails it doesn't keep the lock in place.  
Shutdown process is based on [the phusion image we use](https://github.com/phusion/baseimage-docker/blob/4646d893db9778ff2fd386b387eb5f46b88b92d0/image/bin/my_init#L283) as a base.
Reading the logs during a `make stop`, you can see the shutdown process, including the cleanup part.
```sh
php-fpm_1 …
```
> Clean up install lock on shutdown

- src/planet-4-151612/wordpress/wp-config.php.tmpl
This will prevent the checkbox to allow theme editor for non-logged in from being shown in production environments. It's also checked even if the feature would somehow be turned on on production. See https://github.com/greenpeace/planet4-master-theme/pull/1173/commits/b831e4ff4a289a7a3ed6e95b51bb5a6bc34c8d5e
> Allow turning on theme editor on dev envs

- src/planet-4-151612/wordpress/etc/my_init.d/20_install_wordpress.sh
Ref: https://jira.greenpeace.org/browse/PLANET-6017
> Composer permission to 'app' user are lost when containers are removed and re-created. This happens at any time docker uses docker-compose down && docker-compose up commands.
Running `make down` or `docker-compose down` removes containers; on the next run they are rebuilt. Each time, script `20_install_wordpress.sh` runs; if it does an installation it also fixes permissions issues, but if it finds a wordpress installation it skips all operations in the script.
```console
> make dev
> docker-compose exec -u app php-fpm composer licenses
// display packages licenses
> make down && make up
> docker-compose exec -u app php-fpm composer licenses
// fails
bash: /app/bin/composer: Permission denied
```
Composer is not owned by `app` because …
> PLANET-6017: Give composer script permissions before wp check

- .circleci/config.yml
- .gitignore
- .yamllint
- Makefile
- bin/build.sh
- bin/inc/main
- src/greenpeace-testing/cloudbuild.yaml
- src/greenpeace-testing/hello-world/cloudbuild.yaml
- src/greenpeace-testing/ubuntu/cloudbuild.yaml
- src/greenpeace-testing/ubuntu/templates/Dockerfile.in
- src/planet-4-151612/cloudbuild.yaml
- src/planet-4-151612/ubuntu/cloudbuild.yaml
- src/planet-4-151612/ubuntu/templates/Dockerfile.in
- tests/src/planet-4-151612/php-fpm/tests/00_microscanner.bats
Ref: https://jira.greenpeace.org/browse/PLANET-6051
---
Microscanner is deprecated. Instead we can use Trivy for scanning for vulnerabilities.
We already had Trivy on the CI image. And we also just [updated it](https://github.com/greenpeace/planet4-circleci/commit/70f3b606eeec56c67943d9fc94fc18ea5400a280) to the latest version.
**Testing**
The `scan-wordpress` and all `scan` jobs in [the CI](https://app.circleci.com/pipelines/github/greenpeace/planet4-docker/284/workflows/4068946c-e5c0-4513-b16d-bc97f68a9b5a/jobs/10156/artifacts) should have a vulnerability report, similar to what Microscanner was doing. Added one more step to store it as an artifact.
> PLANET-6051 Replace Microscanner with Trivy

- config.default
- src/planet-4-151612/php-fpm/templates/etc/php/fpm/conf.d/30-elastic-apm-custom.ini.tmpl
- src/planet-4-151612/wordpress/etc/my_init.d/30_install_elastic_apm.sh
- src/planet-4-151612/wordpress/etc/my_init.d/95_elastic_apm.sh
- src/planet-4-151612/wordpress/etc/rc.docker.d/20_elastic_apm.sh
- src/planet-4-151612/wordpress/templates/Dockerfile.in
- src/planet-4-151612/wordpress/templates/README.md.in
- src/planet-4-151612/wordpress/wp-config.php.tmpl
Ref: https://jira.greenpeace.org/browse/PLANET-5963
---
Install APM php agent using their .deb package and doing some basic hash validation. Then use environment variables to populate its custom configuration file.
For used `MYSQL_USER` for setting service name per app. It doesn't seem right, but it's the only variable I tested to give a meaningful value. Not sure why we duplicate config scripts on `my_init.d` and `rc.docker.d`, but I followed existing structure.
> PLANET-5963 Install APM agent and set configuration

- src/planet-4-151612/wordpress/etc/my_init.d/20_install_wordpress.sh
- src/planet-4-151612/wordpress/etc/my_init.d/90_wordpress.sh
Current code overwrites `wp-config.php` file every time the php container starts (start/up/build).  
It stops developers from experimenting on configuration during long developments.  
For [PLANET-6023](https://github.com/greenpeace/planet4-docker-compose/pull/79), it prevents switching between databases and reliably getting the same instance back when you restart docker.
This modification writes a config file in development environment only if it doesn't exist.  
It is limited to development only so that arbitrary configuration cannot be set by accident in production, it will still be overwritten by the container generated one.
- While your containers are running, add a change to your `persistence/app/public/wp-config.php` file.
- Run `make stop && make start`
- your change should have …
> PLANET-6023: Keep wp configuration file between runs

- src/planet-4-151612/wordpress/etc/my_init.d/20_install_wordpress.sh
- src/planet-4-151612/wordpress/etc/my_init.d/90_wordpress.sh
Reverts greenpeace/planet4-docker#70
This change breaks [Acceptance tests](https://app.circleci.com/pipelines/github/greenpeace/planet4-plugin-gutenberg-blocks/4263/workflows/0e8a7b47-955e-43e7-8473-1df3c1f8736f/jobs/15499) in other repos, with message
`php-fpm_1        | Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `db:3306`. This could mean your host’s database server is down.`
I'll check different solutions (implementing the `local` environment keyword looks like the more reliable one)
> Revert "PLANET-6023: Keep wp configuration file between runs"

- src/planet-4-151612/exim/etc/service/exim/run
- src/planet-4-151612/php-fpm/templates/README.md.in
- src/planet-4-151612/wordpress/etc/my_init.d/20_install_wordpress.sh
- src/planet-4-151612/wordpress/etc/my_init.d/90_wordpress.sh
- src/planet-4-151612/wordpress/wp-config.php.tmpl
Related to: https://github.com/greenpeace/planet4-docker-compose/pull/79
Following https://github.com/greenpeace/planet4-docker/pull/70 , this is a different approach implementing a `local` keyword for APP_ENV variable in the php-fpm container.
This time :grimacing:  I think I tested it til the end https://app.circleci.com/pipelines/github/greenpeace/planet4-plugin-gutenberg-blocks/4370/workflows/e7682422-28dc-4f48-a1d2-f2b58ecd8986/jobs/16162 with https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/commit/90ae797cc0ff5dbe01965b192ea47ef3da151958
In addition to this, I'll make a PR modifying the default configuration of APP_ENV in docker-compose.yml
On your local test instance:
- `make down`
- modify your wp-config,php file
- …
> Declare local env and don't overwrite wp-config file

- src/planet-4-151612/wordpress/etc/my_init.d/20_install_wordpress.sh
Local installation with `make dev` generates an error during installation:
> [UnexpectedValueException]
> RecursiveDirectoryIterator::__construct(/app/source/artifacts/): failed to open dir: No such file or directory
Nightly pipeline failing:
https://app.circleci.com/pipelines/github/greenpeace/planet4-docker-compose/558/workflows/b9c819dd-48f6-44f2-934e-b39ffddec1ee/jobs/982
Code related to composer artifacts:
https://github.com/greenpeace/planet4-base/commit/620411d846de17b52aee8b1058e4ae158779e7b6#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34
Creating artifacts directory in advance with proper access rights to fix the error.
- `make dev` on a fresh `planet4-docker-compose` clone currently fails
- `APP_IMAGE=gcr.io/planet-4-151612/wordpress:fix-composer-artifacts …
> Fix composer install error on artifacts directory

- src/planet-4-151612/wordpress/etc/my_init.d/30_install_elastic_apm.sh
- src/planet-4-151612/wordpress/etc/my_init.d/95_elastic_apm.sh
- src/planet-4-151612/wordpress/etc/rc.docker.d/20_elastic_apm.sh
- src/planet-4-151612/wordpress/templates/Dockerfile.in
Ref: https://jira.greenpeace.org/browse/PLANET-5963
APM is not usually used on local environment, adding a variable to its installation process will allow to trigger or skip it, depending on the context.
Test with https://github.com/greenpeace/planet4-docker-compose/compare/planet-5963-cond or configure `INSTALL_APM_AGENT` in your docker-compose.yml file.
- Default `APP_IMAGE=gcr.io/planet-4-151612/wordpress:planet-5963-cond make dev-from-release` won't install APM agent
- `APP_IMAGE=gcr.io/planet-4-151612/wordpress:planet-5963-cond INSTALL_APM_AGENT=true make dev-from-release` installs apm agent, you get logs displaying during install and can check apm files exist in `make php-shell`: `/opt/elastic/apm-agent-php/`
> PLANET-5963: Add condition to APM agent installation

- src/planet-4-151612/wordpress/etc/my_init.d/20_install_wordpress.sh
Ref: https://jira.greenpeace.org/browse/PLANET-6018
Skip lock creation on installation on local environment, so that infinite loop doesn't happen during development
- Run a new install with `APP_IMAGE=gcr.io/planet-4-151612/wordpress:planet-6018 make dev` 
- During installation, check logs with `docker-compose logs -f php-fpm`
- On a usual `make dev`, the php-fpm logs will indicate `php-fpm_1    |   * Creating install lock file: /app/source/.install` (just after `Sleeping x ms ...` and before `Number of files in source folder: 2`
- On this branch, this step never happens
- Running this branch with a different environment will still install the lock, eg `APP_IMAGE=gcr.io/planet-4-151612/wordpress:planet-6018 APP_ENV=develop make dev`
~Note that this step already never happens for `make …
> PLANET-6018: Skip install lock on local environment

- src/planet-4-151612/openresty/etc/nginx/conf.d/security.conf
Ref: https://jira.greenpeace.org/browse/PLANET-5948
---
This header determines what origin information an external site gets when a user is linked there from our websites [Documentation](https://scotthelme.co.uk/a-new-security-header-referrer-policy/). We are defaulting to 'origin-strict' which will only sent the origin domain (not the path) only on https destinations.
- This is [a report](https://securityheaders.com/?q=https%3A%2F%2Fwww.greenpeace.org%2Finternational%2F%2F&hide=on&followRedirects=on) from `international` without the header.
- This is [a report](https://securityheaders.com/?q=https%3A%2F%2Fwww-dev.greenpeace.org%2Fcidev%2F&hide=on&followRedirects=on) from `cidev` with the header.
```
curl -I https://www-dev.greenpeace.org/cidev/
...
referrer-policy: strict-origin
```
> PLANET-5948 Add Referrer-Policy header

- src/planet-4-151612/openresty/etc/nginx/conf.d/security.conf
Ref: https://jira.greenpeace.org/browse/PLANET-5948
---
As a first iteration, this includes a few permissions that can allow
certain browser features that NROs can potentially use when they build
custom blocks and plugins.
This currently runs on `cidev` giving us an "A" rate on the [scan report](https://securityheaders.com/?q=https%3A%2F%2Fwww-dev.greenpeace.org%2Fcidev%2F&hide=on&followRedirects=on).
```
curl -I https://www-dev.greenpeace.org/cidev/
permissions-policy: geolocation=(),sync-xhr=(),microphone=(),camera=(),fullscreen=(),payment=()
```
> PLANET-5948 Add Permission-Policy header

- src/planet-4-151612/wordpress/etc/my_init.d/20_install_wordpress.sh
Get `WP_VERSION` from base composer only when it's not set already. That allows us to override on an NRO or environment level by adding a `WP_VERSION` variable.
In order for this to work we need to remove the fallback value from builder in https://github.com/greenpeace/planet4-builder/pull/87
Not easy to test locally, so I used `cidev` to test it. 
1. First I [added the env varialbe](https://github.com/greenpeace/planet4-cidev/commit/fb7df5c75f2d27bbb82bcaa39a6e746e04988e53) and indeed looking into `make bake` in [CI output](https://app.circleci.com/pipelines/github/greenpeace/planet4-cidev/1295/workflows/0f91a64b-e2eb-4203-9f04-71816d4d7fcb/jobs/3600) you can see: `Using WP_VERSION: 5.8.1`
2. Removed that line and it used the fallback from base repo. Looking into the [CI …
> Allow WP_VERSION override from CI env variable

- src/planet-4-151612/wordpress/etc/my_init.d/20_install_wordpress.sh
Ref: https://jira.greenpeace.org/browse/PLANET-6307
---
Since `make bake` writes after we have merged and rewritten composer files, we can use them to get `wp-version`. This allows to override default base value from an nro repo.
Since we will have https://github.com/greenpeace/planet4-builder/pull/88 in place and environment files will already be merged to composer, we can even override per environment.
> PLANET-6307 Get WP_VERSION from NRO composer or fallback to base

- config.default
- src/planet-4-151612/php-fpm/templates/Dockerfile.in
Ref: https://jira.greenpeace.org/browse/PLANET-6306
- Update PHP version
- Remove php-recode extension, not available on PHP >= 7.4
Function recode is apparently not needed anymore (it was used in the archived project https://github.com/greenpeace/planet4-appengine-phpmyadmin), if it is needed see https://www.php.net/manual/en/recode.installation.php
> PLANET-6306: Switch to PHP 7.4

- src/planet-4-151612/php-fpm/templates/Dockerfile.in
Ref: https://jira.greenpeace.org/browse/PLANET-6432
Doc: https://www.php.net/manual/en/intro.intl.php
Also relevant: https://make.wordpress.org/hosting/2021/05/20/why-hosters-should-install-the-php-intl-extension/
> Add php-intl extension to handle languages breaks/boundaries

- src/planet-4-151612/openresty/templates/etc/nginx/sites-enabled/default-ssl.conf.tmpl
- src/planet-4-151612/openresty/templates/etc/nginx/sites-enabled/default.conf.tmpl
Due to the current issue with the site not showing 404 pages properly. We need to configure a custom 404 page in the landing site. The landing site uses the openresty image from P4 and requires configuration through environment variables. We have to add the environment variable here to configure the 404 page then we can direct the landing page to use the 404.html page included in the repo as the error page. Finally we can configure the landing page as the default backend for nginx so that any requests are routed there and therefore to the custom 404 page.
> Allow configuring a custom 404 page

- src/planet-4-151612/openresty/templates/etc/nginx/server.d/10_php.conf.tmpl
Nginx was caching the EN session token for too long, causing forms to use an expired key and fail.
I'll squash on merge.
> Skip cache for /wp-json/

- src/planet-4-151612/wordpress/wp-config.php.tmpl
Ref: https://wpml.org/documentation/getting-started-guide/string-translation/finding-strings-that-dont-appear-on-the-string-translation-page/#synchronizing-translation-files-for-sites-running-on-multiple-servers
---
This enables WPML String Translation to work with multiple pods.
> Add WPML_ST_SYNC_TRANSLATION_FILES flag

- src/planet-4-151612/openresty/templates/etc/nginx/server.d/00_rewrite_path.conf.tmpl
This PR adds a new location block into openresty that redirects the users explicitly to app_hostpath/wp-admin/ when they hit app_hostpath/wp-admin. I could not identify a more generic way to implement this that easily fits within our current architecture.
Still need to test what happens on sites which do not have an APP_HOSTPATH @comzeradd  do you have any examples ?
Jira https://jira.greenpeace.org/browse/PLANET-6279
> add workaround for wp-admin redirect

- src/planet-4-151612/wordpress/templates/Dockerfile.in
We now need to define the `WP_STATELESS_MEDIA_ROOT_DIR` using wildcards introduced in wp-stateless 3.0.
> Set wp-stateless root dir configuration for 3.2 update

- src/planet-4-151612/php-fpm/templates/Dockerfile.in
Something changed in Ubuntu php packages and 8.1 is pulled in and being used as the default version. Purging makes 7.4 work again.
> Remove php8.1 packages

- src/planet-4-151612/openresty/bin/install_openresty.sh
@comzeradd Thoughts on compiling NGINX with the `--with-debug` flag. Should have negligible performance impact when not in debug mode and means it easier to switch openresty into debugging mode when required (don't have to do a special build and redeploy a site)
More info here: https://docs.nginx.com/nginx/admin-guide/monitoring/debugging/#compiling-nginx-opensource-binary
> compile openresty with debug

- src/planet-4-151612/openresty/etc/nginx/conf.d/security.conf
Ref. https://jira.greenpeace.org/browse/PLANET-6978
The issue is only reproduce on Google Chrome browser, the youtube embed video fullscreen not working.
By changing the `Permissions-Policy: fullscreen` the fullscreen functionality works for chrome browser.
I don't see any harm removing(not restricting the fullscreen) the fullscreen from Permissions-Policy, but if I am missing something please confirm.
Referance: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/fullscreen
> PLANET-6978 Allow browsers fullscreen feature
